// ============================================================
// SamvidhanSaathi — data.js
// Pre-filled content for all 60 curated articles
// Edit this file to update article content
// DO NOT edit index.html for content changes
// ============================================================

const ARTICLE_DATA = {

"1": {
  explain: `<div style="padding:16px">
    <div style="background:var(--surface);border:1px solid var(--border);border-radius:14px;padding:16px;margin-bottom:12px">
      <div style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:0.8px;color:var(--text3);margin-bottom:10px">💡 Simple Explanation</div>
      <p style="font-size:14px;line-height:1.7;color:var(--text2)"><strong>Article 1</strong> declares that India (Bharat) is a <strong>Union of States</strong> — not a federation like USA, but a Union. This one word difference is huge!</p>
      <p style="font-size:14px;line-height:1.7;color:var(--text2)">It also lists the <strong>three types of territories</strong>: States, Union Territories, and territories that may be acquired by India.</p>
      <ul style="font-size:14px;line-height:1.7;color:var(--text2);padding-left:18px;margin-top:8px">
        <li><strong>Why "Union"?</strong> — States cannot secede. India is indestructible.</li>
        <li><strong>Bharat</strong> — the official Hindi name, comes from the legendary king Bharata.</li>
        <li><strong>Territory</strong> — includes mainland + islands + territorial waters</li>
        <li><strong>Acquired territories</strong> — allows India to add new territories (like Goa in 1961, Sikkim in 1975)</li>
      </ul>
    </div>
    <div style="background:var(--accent-soft);border:1px solid var(--accent);border-radius:14px;padding:16px">
      <div style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:0.8px;color:var(--accent);margin-bottom:8px">🏛️ Historical Context</div>
      <p style="font-size:14px;line-height:1.7;color:var(--text2)">During Constituent Assembly debates, Dr. Ambedkar insisted on "Union" not "Federation" — because India's unity must be non-negotiable. The British had left us divided into 550+ princely states. Article 1 was the founding declaration: <em>we are one.</em></p>
    </div>
  </div>`,

  memory: `<div style="padding:16px">
    <div style="background:linear-gradient(135deg,var(--accent-soft),var(--bg2));border:1px solid var(--accent);border-radius:14px;padding:16px;margin-bottom:12px">
      <div style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:1px;color:var(--accent);margin-bottom:10px">🧠 Memory Trick</div>
      <p style="font-size:14px;line-height:1.7;color:var(--text);font-style:italic">"Article <strong>1</strong> = <strong>ONE</strong> India. Article 1 is literally about India being ONE Union. The number itself is the trick!"</p>
    </div>
    <div style="background:linear-gradient(135deg,#FF6B6B15,#FFE66D15);border:1px solid #FF6B6B40;border-radius:14px;padding:14px;margin-bottom:12px">
      <div style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:1px;color:#E05050;margin-bottom:8px">🎬 Bollywood Hook</div>
      <p style="font-size:14px;line-height:1.7;color:var(--text2)">Remember the song <strong>"Mere Desh Ki Dharti"</strong> or Shah Rukh Khan's dialogue — <em>"Yeh India hai mere dost"</em>. Article 1 is that declaration — <strong>India is India</strong>, one union, indivisible. Like how Bollywood always ends with unity — Article 1 starts with it!</p>
    </div>
    <div style="background:var(--surface);border:1px solid var(--border);border-radius:14px;padding:14px">
      <div style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:0.8px;color:var(--text3);margin-bottom:8px">🖼️ Visual Image</div>
      <p style="font-size:14px;line-height:1.7;color:var(--text2)">Picture the map of India with the number "1" stamped on it. <strong>One map. One Union. Article 1.</strong></p>
    </div>
  </div>`,

  exam: `<div style="padding:16px">
    <div style="background:var(--surface);border:1px solid var(--border);border-radius:14px;padding:16px;margin-bottom:12px">
      <div style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:0.8px;color:var(--text3);margin-bottom:10px">🎓 Prelims Angle</div>
      <ul style="font-size:14px;line-height:1.7;color:var(--text2);padding-left:18px">
        <li>Q: India is described as a ___ of States → <strong>Union</strong> (NOT Federation)</li>
        <li>Q: Which article names India as "Bharat"? → <strong>Article 1</strong></li>
        <li>Q: Types of territories under Article 1 → States, UTs, Acquired territories</li>
        <li>Classic trap: "Federal" vs "Union" — always choose Union</li>
      </ul>
    </div>
    <div style="background:var(--green-soft);border:1px solid var(--green);border-radius:14px;padding:16px;margin-bottom:12px">
      <div style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:0.8px;color:var(--green);margin-bottom:8px">📝 Mains Angle (GS-II)</div>
      <p style="font-size:14px;line-height:1.7;color:var(--text2)">Use in answers on: Centre-State relations, federalism, territorial integrity, integration of princely states. Quote: <em>"India, that is Bharat, shall be a Union of States"</em> — shows framers chose unity over confederation.</p>
    </div>
    <div style="background:var(--red-soft);border:1px solid var(--red);border-radius:14px;padding:14px">
      <div style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:0.8px;color:var(--red);margin-bottom:8px">⚠️ Common Mistake</div>
      <p style="font-size:14px;color:var(--text2)">Students write "Federation of States" — WRONG. It's <strong>Union of States</strong>. This distinction is asked almost every year.</p>
    </div>
  </div>`,

  laws: `<div style="padding:16px">
    <div style="border-left:2px solid var(--gold);padding:10px 0 10px 14px;margin-bottom:12px">
      <div style="font-size:13px;font-weight:600;color:var(--text)">State of West Bengal v. Union of India</div>
      <div style="font-size:11px;color:var(--gold);font-weight:600">1963</div>
      <div style="font-size:12px;color:var(--text2);margin-top:4px;line-height:1.5">SC held that India is NOT a true federation — States cannot challenge Parliament's sovereign power. Confirmed the "Union" nature of India under Article 1.</div>
    </div>
    <div style="border-left:2px solid var(--gold);padding:10px 0 10px 14px;margin-bottom:12px">
      <div style="font-size:13px;font-weight:600;color:var(--text)">Berubari Union Case</div>
      <div style="font-size:11px;color:var(--gold);font-weight:600">1960</div>
      <div style="font-size:12px;color:var(--text2);margin-top:4px;line-height:1.5">SC ruled that ceding territory to a foreign country requires constitutional amendment. Established that Indian territory is protected — relevant to Article 1's listing of territories.</div>
    </div>
    <div style="border-left:2px solid var(--gold);padding:10px 0 10px 14px">
      <div style="font-size:13px;font-weight:600;color:var(--text)">In Re: The Special Courts Bill</div>
      <div style="font-size:11px;color:var(--gold);font-weight:600">1979</div>
      <div style="font-size:12px;color:var(--text2);margin-top:4px;line-height:1.5">Reinforced the unitary character of India — while States have powers, the Union is supreme in maintaining territorial integrity.</div>
    </div>
  </div>`,

  amend: `<div style="padding:16px">
    <div style="background:var(--surface);border:1px solid var(--border);border-radius:14px;padding:16px">
      <p style="font-size:14px;line-height:1.7;color:var(--text2)">Article 1 itself has <strong>not been directly amended</strong>, but the First Schedule (which lists the States and UTs that Article 1 refers to) has been amended multiple times:</p>
      <div style="display:flex;gap:10px;padding:10px 0;border-bottom:1px solid var(--border)">
        <span style="font-family:var(--font-mono);font-size:12px;font-weight:600;color:var(--accent);background:var(--accent-soft);padding:3px 8px;border-radius:8px;white-space:nowrap">7th Amendment, 1956</span>
        <span style="font-size:13px;color:var(--text2)">Reorganised states on linguistic basis — major restructuring</span>
      </div>
      <div style="display:flex;gap:10px;padding:10px 0;border-bottom:1px solid var(--border)">
        <span style="font-family:var(--font-mono);font-size:12px;font-weight:600;color:var(--accent);background:var(--accent-soft);padding:3px 8px;border-radius:8px;white-space:nowrap">36th Amendment, 1975</span>
        <span style="font-size:13px;color:var(--text2)">Sikkim added as 22nd State of India</span>
      </div>
      <div style="display:flex;gap:10px;padding:10px 0">
        <span style="font-family:var(--font-mono);font-size:12px;font-weight:600;color:var(--accent);background:var(--accent-soft);padding:3px 8px;border-radius:8px;white-space:nowrap">100th Amendment, 2015</span>
        <span style="font-size:13px;color:var(--text2)">Land boundary agreement with Bangladesh — territories exchanged</span>
      </div>
    </div>
  </div>`,

  trivia: `<div style="padding:16px">
    <div style="background:var(--surface);border:1px solid var(--border);border-radius:14px;padding:16px">
      <ul style="font-size:14px;line-height:1.9;color:var(--text2);padding-left:18px">
        <li>🤔 The name <strong>"Bharat"</strong> comes from the legendary Emperor Bharata, son of King Dushyanta and Shakuntala — the same story in Kalidasa's Abhijnanasakuntalam</li>
        <li>🗺️ When the Constitution was adopted, India had <strong>14 States and 6 Part C States</strong>. Today we have 28 States and 8 UTs</li>
        <li>⚡ During Constituent Assembly debates, some members wanted <strong>"Hindustan"</strong> as the name — but "India, that is Bharat" was the compromise</li>
        <li>🏝️ India's territory includes islands up to <strong>1,200 km away</strong> — Andaman & Nicobar and Lakshadweep</li>
        <li>📜 Article 1 is the FIRST operative article — the Preamble comes before it but isn't technically an article</li>
      </ul>
    </div>
  </div>`,

  official: `<div style="padding:16px">
    <div style="font-family:var(--font-mono);font-size:13px;line-height:1.8;color:var(--text2);background:var(--bg2);border-radius:8px;padding:14px;border-left:3px solid var(--accent);margin-bottom:16px">
      <strong>Article 1. Name and territory of the Union —</strong><br><br>
      (1) India, that is Bharat, shall be a Union of States.<br><br>
      (2) The States and the territories thereof shall be as specified in the First Schedule.<br><br>
      (3) The territory of India shall comprise —<br>
      &nbsp;&nbsp;(a) the territories of the States;<br>
      &nbsp;&nbsp;(b) the Union territories specified in the First Schedule; and<br>
      &nbsp;&nbsp;(c) such other territories as may be acquired.
    </div>
    <div style="background:var(--surface);border:1px solid var(--border);border-radius:14px;padding:14px">
      <div style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:0.8px;color:var(--text3);margin-bottom:8px">Plain English Translation</div>
      <p style="font-size:13px;line-height:1.7;color:var(--text2)"><strong>Clause 1:</strong> Our country's official names are "India" (English) and "Bharat" (Hindi). It is a Union — states cannot break away.</p>
      <p style="font-size:13px;line-height:1.7;color:var(--text2)"><strong>Clause 2:</strong> The list of states and their boundaries is in Schedule 1 of the Constitution.</p>
      <p style="font-size:13px;line-height:1.7;color:var(--text2)"><strong>Clause 3:</strong> India's territory = all state territories + union territories + any future acquired territories.</p>
    </div>
  </div>`
},

"3": {
  explain: `<div style="padding:16px"><div style="background:var(--surface);border:1px solid var(--border);border-radius:14px;padding:16px;margin-bottom:12px"><div style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:0.8px;color:var(--text3);margin-bottom:10px">💡 Simple Explanation</div><p style="font-size:14px;line-height:1.7;color:var(--text2)">Article 3 gives <strong>Parliament the power to redraw the map of India</strong> — create new states, merge existing ones, change boundaries and names. The most powerful map-editing article!</p><ul style="font-size:14px;line-height:1.7;color:var(--text2);padding-left:18px;margin-top:8px"><li>Form a new State by separation of territory from any State</li><li>Unite two or more States or parts of States</li><li>Increase or diminish the area of any State</li><li>Alter the boundaries of any State</li><li>Alter the name of any State</li></ul></div><div style="background:var(--accent-soft);border:1px solid var(--accent);border-radius:14px;padding:16px"><div style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:0.8px;color:var(--accent);margin-bottom:8px">⚠️ Key Condition</div><p style="font-size:14px;line-height:1.7;color:var(--text2)">Before introducing such a Bill, the President must refer it to the affected State Legislature for its <strong>opinion</strong> — but Parliament is NOT bound by that opinion. States cannot veto!</p></div></div>`,
  memory: `<div style="padding:16px"><div style="background:linear-gradient(135deg,var(--accent-soft),var(--bg2));border:1px solid var(--accent);border-radius:14px;padding:16px;margin-bottom:12px"><div style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:1px;color:var(--accent);margin-bottom:10px">🧠 Memory Trick</div><p style="font-size:14px;line-height:1.7;color:var(--text);font-style:italic">"Article 3 = <strong>3Rs of Map-Making</strong>: Reshape, Rename, Reorganise. Parliament is India's map editor!"</p></div><div style="background:linear-gradient(135deg,#FF6B6B15,#FFE66D15);border:1px solid #FF6B6B40;border-radius:14px;padding:14px"><div style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:1px;color:#E05050;margin-bottom:8px">🎬 Bollywood Hook</div><p style="font-size:14px;line-height:1.7;color:var(--text2)">Remember when Telangana was carved out of Andhra Pradesh in 2014? That was Article 3 in action! Like a film director who can reshoot any scene — Parliament can redraw any state boundary using Article 3.</p></div></div>`,
  exam: `<div style="padding:16px"><div style="background:var(--surface);border:1px solid var(--border);border-radius:14px;padding:16px;margin-bottom:12px"><div style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:0.8px;color:var(--text3);margin-bottom:10px">🎓 Exam Angle</div><ul style="font-size:14px;line-height:1.7;color:var(--text2);padding-left:18px"><li>Article 3 bills require <strong>President's recommendation</strong> before introduction</li><li>State legislature opinion is <strong>sought but NOT binding</strong> — classic UPSC trap!</li><li>Simple majority in Parliament is sufficient — NOT special majority</li><li>Used for: Telangana (2014), Jharkhand (2000), Uttarakhand (2000), Chhattisgarh (2000)</li></ul></div><div style="background:var(--red-soft);border:1px solid var(--red);border-radius:14px;padding:14px"><div style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:0.8px;color:var(--red);margin-bottom:8px">⚠️ Common Mistake</div><p style="font-size:14px;color:var(--text2)">Students confuse Article 3 (Parliament's power) with Article 368 (Amendment). Article 3 only needs simple majority, not special majority!</p></div></div>`,
  laws: `<div style="padding:16px"><div style="border-left:2px solid var(--gold);padding:10px 0 10px 14px;margin-bottom:12px"><div style="font-size:13px;font-weight:600;color:var(--text)">Babulal Parate v. State of Bombay</div><div style="font-size:11px;color:var(--gold);font-weight:600">1960</div><div style="font-size:12px;color:var(--text2);margin-top:4px;line-height:1.5">SC upheld Parliament's power to reorganise states under Article 3. State legislature's opinion is merely consultative — Parliament has final say.</div></div><div style="border-left:2px solid var(--gold);padding:10px 0 10px 14px"><div style="font-size:13px;font-weight:600;color:var(--text)">State of Rajasthan v. Union of India</div><div style="font-size:11px;color:var(--gold);font-weight:600">1977</div><div style="font-size:12px;color:var(--text2);margin-top:4px;line-height:1.5">Reaffirmed that India is a Union where Centre has overriding power on territorial matters. States have no right to resist reorganisation.</div></div></div>`,
  amend: `<div style="padding:16px"><div style="background:var(--surface);border:1px solid var(--border);border-radius:14px;padding:16px"><p style="font-size:14px;line-height:1.7;color:var(--text2)">Article 3 has been <strong>amended once</strong>:</p><div style="display:flex;gap:10px;padding:10px 0"><span style="font-family:var(--font-mono);font-size:12px;font-weight:600;color:var(--accent);background:var(--accent-soft);padding:3px 8px;border-radius:8px;white-space:nowrap">5th Amendment, 1955</span><span style="font-size:13px;color:var(--text2)">Added the requirement that President must refer the bill to the State Legislature and specify a time limit for giving opinion</span></div></div></div>`,
  trivia: `<div style="padding:16px"><div style="background:var(--surface);border:1px solid var(--border);border-radius:14px;padding:16px"><ul style="font-size:14px;line-height:1.9;color:var(--text2);padding-left:18px"><li>🗺️ Since independence, Article 3 has been used to create <strong>8 new states</strong> — most recently Telangana in 2014</li><li>⚡ India had 14 states at independence. Now it has 28 states and 8 UTs</li><li>🏔️ Uttarakhand was originally called "Uttaranchal" when carved from UP in 2000 — renamed in 2007 using Article 3</li><li>📊 The States Reorganisation Commission (1953-55) used Article 3 to completely redraw India's map on linguistic lines</li></ul></div></div>`,
  official: `<div style="padding:16px"><div style="font-family:var(--font-mono);font-size:13px;line-height:1.8;color:var(--text2);background:var(--bg2);border-radius:8px;padding:14px;border-left:3px solid var(--accent);margin-bottom:16px"><strong>Article 3. Formation of new States and alteration of areas, boundaries or names of existing States —</strong><br><br>Parliament may by law—<br>(a) form a new State by separation of territory from any State or by uniting two or more States or parts of States or by uniting any territory to a part of any State;<br>(b) increase the area of any State;<br>(c) diminish the area of any State;<br>(d) alter the boundaries of any State;<br>(e) alter the name of any State.</div><div style="background:var(--surface);border:1px solid var(--border);border-radius:14px;padding:14px"><div style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:0.8px;color:var(--text3);margin-bottom:8px">Plain English</div><p style="font-size:13px;line-height:1.7;color:var(--text2)">Parliament can create new states, merge states, increase/decrease state areas, change boundaries, and rename states — but must ask the concerned state legislature for its opinion first (though the opinion is not binding).</p></div></div>`
},

"12": {
  explain: `<div style="padding:16px"><div style="background:var(--surface);border:1px solid var(--border);border-radius:14px;padding:16px;margin-bottom:12px"><div style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:0.8px;color:var(--text3);margin-bottom:10px">💡 Simple Explanation</div><p style="font-size:14px;line-height:1.7;color:var(--text2)">Article 12 is the <strong>gatekeeper of Part III</strong>. It defines what "State" means for the purpose of Fundamental Rights. You can only sue for FR violations against a "State" as defined here.</p><p style="font-size:14px;line-height:1.7;color:var(--text2);margin-top:8px"><strong>State includes:</strong></p><ul style="font-size:14px;line-height:1.7;color:var(--text2);padding-left:18px"><li>Government and Parliament of India</li><li>Government and Legislature of each State</li><li>All local authorities (municipalities, panchayats)</li><li>"Other authorities" — this has been interpreted very broadly by courts</li></ul></div><div style="background:var(--gold-soft);border:1px solid var(--gold);border-radius:14px;padding:14px"><p style="font-size:14px;line-height:1.7;color:var(--text2)">🔑 <strong>Key Question:</strong> Is BCCI a "State"? Is LIC? Is ONGC? Courts have developed tests to decide this — making Article 12 one of the most litigated articles!</p></div></div>`,
  memory: `<div style="padding:16px"><div style="background:linear-gradient(135deg,var(--accent-soft),var(--bg2));border:1px solid var(--accent);border-radius:14px;padding:16px;margin-bottom:12px"><div style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:1px;color:var(--accent);margin-bottom:10px">🧠 Memory Trick</div><p style="font-size:14px;line-height:1.7;color:var(--text);font-style:italic">"Article 12 = <strong>12 gates to the kingdom of Fundamental Rights</strong>. To enter, you must face the State. Article 12 tells you who the State is."</p></div><div style="background:linear-gradient(135deg,#FF6B6B15,#FFE66D15);border:1px solid #FF6B6B40;border-radius:14px;padding:14px"><div style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:1px;color:#E05050;margin-bottom:8px">🎬 Bollywood Hook</div><p style="font-size:14px;line-height:1.7;color:var(--text2)">In every Bollywood film, the villain has henchmen. Article 12 defines who counts as the villain's (State's) henchmen — so you know who to fight against for your rights! Just like identifying the "system" in Rang De Basanti.</p></div></div>`,
  exam: `<div style="padding:16px"><div style="background:var(--surface);border:1px solid var(--border);border-radius:14px;padding:16px;margin-bottom:12px"><div style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:0.8px;color:var(--text3);margin-bottom:10px">🎓 Exam Angle</div><ul style="font-size:14px;line-height:1.7;color:var(--text2);padding-left:18px"><li>"Other authorities" test: <strong>Government control + public function</strong></li><li>UPSC frequently asks: Is X a State under Article 12?</li><li>LIC ✅, ONGC ✅, BCCI ❌ (private body), Universities — depends on funding</li><li>Article 12 definition applies ONLY to Part III — not the whole Constitution</li></ul></div><div style="background:var(--red-soft);border:1px solid var(--red);border-radius:14px;padding:14px"><div style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:0.8px;color:var(--red);margin-bottom:8px">⚠️ Classic Trap</div><p style="font-size:14px;color:var(--text2)">Article 12 definition of "State" is ONLY for Part III (Fundamental Rights). For other parts, "State" means state government in its normal sense.</p></div></div>`,
  laws: `<div style="padding:16px"><div style="border-left:2px solid var(--gold);padding:10px 0 10px 14px;margin-bottom:12px"><div style="font-size:13px;font-weight:600;color:var(--text)">Rajasthan State Electricity Board v. Mohan Lal</div><div style="font-size:11px;color:var(--gold);font-weight:600">1967</div><div style="font-size:12px;color:var(--text2);margin-top:4px;line-height:1.5">SC held that "other authorities" includes statutory bodies created for public purposes. Electricity board = State under Article 12.</div></div><div style="border-left:2px solid var(--gold);padding:10px 0 10px 14px;margin-bottom:12px"><div style="font-size:13px;font-weight:600;color:var(--text)">Sukhdev Singh v. Bhagatram</div><div style="font-size:11px;color:var(--gold);font-weight:600">1975</div><div style="font-size:12px;color:var(--text2);margin-top:4px;line-height:1.5">LIC, ONGC, IFC are "State" under Article 12 — they have statutory character and perform public duties.</div></div><div style="border-left:2px solid var(--gold);padding:10px 0 10px 14px"><div style="font-size:13px;font-weight:600;color:var(--text)">Ajay Hasia v. Khalid Mujib</div><div style="font-size:11px;color:var(--gold);font-weight:600">1981</div><div style="font-size:12px;color:var(--text2);margin-top:4px;line-height:1.5">Laid down the "government control" test — if government has deep pervasive control, the body is "State" under Article 12. Landmark test still used today.</div></div></div>`,
  amend: `<div style="padding:16px"><div style="background:var(--surface);border:1px solid var(--border);border-radius:14px;padding:16px"><p style="font-size:14px;line-height:1.7;color:var(--text2)">Article 12 has <strong>never been amended</strong>. It remains exactly as drafted by the Constituent Assembly in 1949. The expansion of its meaning has happened purely through judicial interpretation.</p></div></div>`,
  trivia: `<div style="padding:16px"><div style="background:var(--surface);border:1px solid var(--border);border-radius:14px;padding:16px"><ul style="font-size:14px;line-height:1.9;color:var(--text2);padding-left:18px"><li>🏏 The BCCI controversy — courts debated for years whether it's a "State". Currently held as NOT a State since it's a private body with no statutory backing</li><li>📚 Universities funded by government ARE State; private unaided universities generally are NOT</li><li>🔑 The phrase "other authorities" has generated hundreds of cases — it's one of the most litigated phrases in Indian constitutional law</li><li>⚖️ Article 12 was inspired by the Irish Constitution's definition of "organs of State"</li></ul></div></div>`,
  official: `<div style="padding:16px"><div style="font-family:var(--font-mono);font-size:13px;line-height:1.8;color:var(--text2);background:var(--bg2);border-radius:8px;padding:14px;border-left:3px solid var(--accent);margin-bottom:16px"><strong>Article 12. Definition —</strong><br><br>In this Part, unless the context otherwise requires, "the State" includes the Government and Parliament of India and the Government and the Legislature of each of the States and all local or other authorities within the territory of India or under the control of the Government of India.</div><div style="background:var(--surface);border:1px solid var(--border);border-radius:14px;padding:14px"><div style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:0.8px;color:var(--text3);margin-bottom:8px">Plain English</div><p style="font-size:13px;line-height:1.7;color:var(--text2)">For Fundamental Rights purposes, "State" means: Central Government + Parliament + State Governments + State Legislatures + All local bodies (municipalities, panchayats) + Any other authority under government control.</p></div></div>`
},

"14": {
  explain: `<div style="padding:16px"><div style="background:var(--surface);border:1px solid var(--border);border-radius:14px;padding:16px;margin-bottom:12px"><div style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:0.8px;color:var(--text3);margin-bottom:10px">💡 Simple Explanation</div><p style="font-size:14px;line-height:1.7;color:var(--text2)">Article 14 has <strong>two golden principles</strong>:</p><ul style="font-size:14px;line-height:1.7;color:var(--text2);padding-left:18px;margin-top:8px"><li><strong>Equality before law</strong> — British concept (negative equality) — State cannot discriminate</li><li><strong>Equal protection of laws</strong> — American concept (positive equality) — equals must be treated equally, unequals may be treated differently</li></ul><p style="font-size:14px;line-height:1.7;color:var(--text2);margin-top:8px">The key insight: Article 14 <strong>does NOT mean everyone gets identical treatment</strong>. Reasonable classification is allowed!</p></div><div style="background:var(--accent-soft);border:1px solid var(--accent);border-radius:14px;padding:14px"><p style="font-size:14px;line-height:1.7;color:var(--text2)">🔑 <strong>Reasonable Classification Test:</strong><br>1. Intelligible differentia (clear basis of classification)<br>2. Rational nexus to the objective of the law</p></div></div>`,
  memory: `<div style="padding:16px"><div style="background:linear-gradient(135deg,var(--accent-soft),var(--bg2));border:1px solid var(--accent);border-radius:14px;padding:16px;margin-bottom:12px"><div style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:1px;color:var(--accent);margin-bottom:10px">🧠 Memory Trick</div><p style="font-size:14px;line-height:1.7;color:var(--text);font-style:italic">"Article <strong>14</strong> = <strong>1</strong> law for <strong>4</strong> corners of India. Everyone is equal before the same law."</p></div><div style="background:linear-gradient(135deg,#FF6B6B15,#FFE66D15);border:1px solid #FF6B6B40;border-radius:14px;padding:14px"><div style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:1px;color:#E05050;margin-bottom:8px">🎬 Bollywood Hook</div><p style="font-size:14px;line-height:1.7;color:var(--text2)">Remember the scene in <strong>Pink (2016)</strong> — "No means No" applies to everyone equally, rich or poor, male or female. That's Article 14! The law doesn't see your face or your wallet.</p></div></div>`,
  exam: `<div style="padding:16px"><div style="background:var(--surface);border:1px solid var(--border);border-radius:14px;padding:16px;margin-bottom:12px"><div style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:0.8px;color:var(--text3);margin-bottom:10px">🎓 Exam Angle</div><ul style="font-size:14px;line-height:1.7;color:var(--text2);padding-left:18px"><li>Article 14 applies to both <strong>citizens AND foreigners</strong> — uses "person" not "citizen"</li><li>Reasonable classification IS allowed under Article 14</li><li>Two conditions: Intelligible differentia + Rational nexus</li><li>Article 14 is the basis of the <strong>doctrine of non-arbitrariness</strong></li></ul></div></div>`,
  laws: `<div style="padding:16px"><div style="border-left:2px solid var(--gold);padding:10px 0 10px 14px;margin-bottom:12px"><div style="font-size:13px;font-weight:600;color:var(--text)">State of West Bengal v. Anwar Ali Sarkar</div><div style="font-size:11px;color:var(--gold);font-weight:600">1952</div><div style="font-size:12px;color:var(--text2);margin-top:4px;line-height:1.5">Established the "reasonable classification" test for Article 14. Classification must have intelligible differentia with rational nexus to legislative objective.</div></div><div style="border-left:2px solid var(--gold);padding:10px 0 10px 14px;margin-bottom:12px"><div style="font-size:13px;font-weight:600;color:var(--text)">E.P. Royappa v. State of Tamil Nadu</div><div style="font-size:11px;color:var(--gold);font-weight:600">1974</div><div style="font-size:12px;color:var(--text2);margin-top:4px;line-height:1.5">Expanded Article 14 beyond classification — "Equality is antithetic to arbitrariness." Any arbitrary state action violates Article 14.</div></div><div style="border-left:2px solid var(--gold);padding:10px 0 10px 14px"><div style="font-size:13px;font-weight:600;color:var(--text)">Maneka Gandhi v. Union of India</div><div style="font-size:11px;color:var(--gold);font-weight:600">1978</div><div style="font-size:12px;color:var(--text2);margin-top:4px;line-height:1.5">Articles 14, 19 and 21 form a "golden triangle" — they must be read together. A law violating one likely violates all three.</div></div></div>`,
  amend: `<div style="padding:16px"><div style="background:var(--surface);border:1px solid var(--border);border-radius:14px;padding:16px"><p style="font-size:14px;line-height:1.7;color:var(--text2)">Article 14 has <strong>never been directly amended</strong>. However, certain laws were placed in the <strong>Ninth Schedule</strong> (via 1st Amendment) to protect them from Article 14 challenges. The 44th Amendment (1978) and Kesavananda Bharati case (1973) established that Article 14 is part of the <strong>Basic Structure</strong> and cannot be abrogated even by amendment.</p></div></div>`,
  trivia: `<div style="padding:16px"><div style="background:var(--surface);border:1px solid var(--border);border-radius:14px;padding:16px"><ul style="font-size:14px;line-height:1.9;color:var(--text2);padding-left:18px"><li>⚖️ "Equality before law" is a <strong>British concept</strong> from Dicey's Rule of Law; "Equal protection of laws" is from the <strong>14th Amendment of the US Constitution</strong></li><li>🔑 Article 14 is part of the <strong>Basic Structure</strong> — Parliament cannot destroy it even with 100% majority</li><li>🌍 India's Article 14 is considered more robust than many democracies because it combines both negative and positive equality</li><li>📊 Article 14 is the most cited article in Indian courts — virtually every constitutional challenge involves it</li></ul></div></div>`,
  official: `<div style="padding:16px"><div style="font-family:var(--font-mono);font-size:13px;line-height:1.8;color:var(--text2);background:var(--bg2);border-radius:8px;padding:14px;border-left:3px solid var(--accent);margin-bottom:16px"><strong>Article 14. Equality before law —</strong><br><br>The State shall not deny to any person equality before the law or the equal protection of the laws within the territory of India.</div><div style="background:var(--surface);border:1px solid var(--border);border-radius:14px;padding:14px"><div style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:0.8px;color:var(--text3);margin-bottom:8px">Plain English</div><p style="font-size:13px;line-height:1.7;color:var(--text2)"><strong>Equality before law:</strong> No one is above the law — not even the Prime Minister.<br><strong>Equal protection:</strong> Similar people must be treated similarly by the law.</p></div></div>`
},

"17": {
  explain: `<div style="padding:16px"><div style="background:var(--surface);border:1px solid var(--border);border-radius:14px;padding:16px;margin-bottom:12px"><div style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:0.8px;color:var(--text3);margin-bottom:10px">💡 Simple Explanation</div><p style="font-size:14px;line-height:1.7;color:var(--text2)">Article 17 <strong>abolishes untouchability</strong> — one of the most revolutionary social reforms in any constitution worldwide. It doesn't just ban discrimination — it makes practising untouchability a <strong>punishable offence</strong>.</p><ul style="font-size:14px;line-height:1.7;color:var(--text2);padding-left:18px;margin-top:8px"><li>Untouchability is abolished</li><li>Its practice in any form is forbidden</li><li>Enforcement of any disability arising from untouchability is an offence</li></ul></div><div style="background:var(--green-soft);border:1px solid var(--green);border-radius:14px;padding:14px"><p style="font-size:14px;line-height:1.7;color:var(--text2)">✅ <strong>Key law:</strong> Protection of Civil Rights Act, 1955 (earlier Untouchability Offences Act) gives teeth to Article 17. Offences are cognizable and punishable.</p></div></div>`,
  memory: `<div style="padding:16px"><div style="background:linear-gradient(135deg,var(--accent-soft),var(--bg2));border:1px solid var(--accent);border-radius:14px;padding:16px;margin-bottom:12px"><div style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:1px;color:var(--accent);margin-bottom:10px">🧠 Memory Trick</div><p style="font-size:14px;line-height:1.7;color:var(--text);font-style:italic">"Article <strong>17</strong> = <strong>17 crore Dalits freed</strong>. The number 17 sounds like 'satrah' — remember 'Sat' (truth) + 'Rah' (path) — the truth path of equality for Dalits."</p></div><div style="background:linear-gradient(135deg,#FF6B6B15,#FFE66D15);border:1px solid #FF6B6B40;border-radius:14px;padding:14px"><div style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:1px;color:#E05050;margin-bottom:8px">🎬 Bollywood Hook</div><p style="font-size:14px;line-height:1.7;color:var(--text2)">The film <strong>Sairat (2016)</strong> and <strong>Article 15 (2019)</strong> powerfully show caste discrimination. Article 17 is Dr. Ambedkar's personal victory — he himself was a victim of untouchability and ensured it was constitutionally abolished.</p></div></div>`,
  exam: `<div style="padding:16px"><div style="background:var(--surface);border:1px solid var(--border);border-radius:14px;padding:16px;margin-bottom:12px"><div style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:0.8px;color:var(--text3);margin-bottom:10px">🎓 Exam Angle</div><ul style="font-size:14px;line-height:1.7;color:var(--text2);padding-left:18px"><li>Article 17 is enforceable against <strong>private individuals too</strong> — not just State action (unlike most FRs)</li><li>Associated law: <strong>Protection of Civil Rights Act 1955</strong> and SC/ST (Prevention of Atrocities) Act 1989</li><li>Offences are <strong>cognizable</strong> (police can arrest without warrant)</li><li>Article 17 is absolute — <strong>NO reasonable restrictions</strong></li></ul></div></div>`,
  laws: `<div style="padding:16px"><div style="border-left:2px solid var(--gold);padding:10px 0 10px 14px;margin-bottom:12px"><div style="font-size:13px;font-weight:600;color:var(--text)">Devarajiah v. B. Padmanna</div><div style="font-size:11px;color:var(--gold);font-weight:600">1958</div><div style="font-size:12px;color:var(--text2);margin-top:4px;line-height:1.5">Court held that the term "untouchability" in Article 17 refers to social practices based on caste, not just religious disabilities.</div></div><div style="border-left:2px solid var(--gold);padding:10px 0 10px 14px"><div style="font-size:13px;font-weight:600;color:var(--text)">State of Karnataka v. Appa Balu Ingale</div><div style="font-size:11px;color:var(--gold);font-weight:600">1993</div><div style="font-size:12px;color:var(--text2);margin-top:4px;line-height:1.5">SC held that practising untouchability violates Article 17 even when done by private parties — the article has horizontal application.</div></div></div>`,
  amend: `<div style="padding:16px"><div style="background:var(--surface);border:1px solid var(--border);border-radius:14px;padding:16px"><p style="font-size:14px;line-height:1.7;color:var(--text2)">Article 17 has <strong>never been amended</strong>. It stands exactly as Dr. Ambedkar drafted it. It is considered part of the Basic Structure of the Constitution.</p></div></div>`,
  trivia: `<div style="padding:16px"><div style="background:var(--surface);border:1px solid var(--border);border-radius:14px;padding:16px"><ul style="font-size:14px;line-height:1.9;color:var(--text2);padding-left:18px"><li>✊ Dr. B.R. Ambedkar was personally affected by untouchability — he was made to sit separately and couldn't touch the water pot in school</li><li>📜 Article 17 is one of the few FRs that applies horizontally — against private citizens, not just the State</li><li>🌍 Very few constitutions in the world have such an explicit abolition of a social practice as a fundamental right</li><li>⚖️ The Protection of Civil Rights Act 1955 was later strengthened by the SC/ST (Prevention of Atrocities) Act 1989</li></ul></div></div>`,
  official: `<div style="padding:16px"><div style="font-family:var(--font-mono);font-size:13px;line-height:1.8;color:var(--text2);background:var(--bg2);border-radius:8px;padding:14px;border-left:3px solid var(--accent);margin-bottom:16px"><strong>Article 17. Abolition of Untouchability —</strong><br><br>"Untouchability" is abolished and its practice in any form is forbidden. The enforcement of any disability arising out of "Untouchability" shall be an offence punishable in accordance with law.</div></div>`
},

"19": {
  explain: `<div style="padding:16px"><div style="background:var(--surface);border:1px solid var(--border);border-radius:14px;padding:16px;margin-bottom:12px"><div style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:0.8px;color:var(--text3);margin-bottom:10px">💡 Simple Explanation</div><p style="font-size:14px;line-height:1.7;color:var(--text2)">Article 19 guarantees <strong>6 freedoms</strong> to citizens (not foreigners). Originally 7, but the right to property (19(1)(f)) was removed by the 44th Amendment 1978.</p><ul style="font-size:14px;line-height:1.7;color:var(--text2);padding-left:18px;margin-top:8px"><li>19(1)(a) — Freedom of speech and expression</li><li>19(1)(b) — Freedom to assemble peacefully</li><li>19(1)(c) — Freedom to form associations or unions</li><li>19(1)(d) — Freedom to move freely throughout India</li><li>19(1)(e) — Freedom to reside and settle anywhere in India</li><li>19(1)(g) — Freedom to practise any profession or carry on any trade</li></ul></div><div style="background:var(--gold-soft);border:1px solid var(--gold);border-radius:14px;padding:14px"><p style="font-size:14px;line-height:1.7;color:var(--text2)">⚠️ All 6 freedoms can be <strong>reasonably restricted</strong> by the State — they are not absolute!</p></div></div>`,
  memory: `<div style="padding:16px"><div style="background:linear-gradient(135deg,var(--accent-soft),var(--bg2));border:1px solid var(--accent);border-radius:14px;padding:16px;margin-bottom:12px"><div style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:1px;color:var(--accent);margin-bottom:10px">🧠 Memory Trick</div><p style="font-size:14px;line-height:1.7;color:var(--text);font-style:italic">"SAMRP-T: <strong>S</strong>peak, <strong>A</strong>ssemble, <strong>M</strong>ove, <strong>R</strong>eside, <strong>P</strong>rofession, <strong>T</strong>rade/Association. Article 19 = 6 SAMRPTs of freedom!"</p></div><div style="background:linear-gradient(135deg,#FF6B6B15,#FFE66D15);border:1px solid #FF6B6B40;border-radius:14px;padding:14px"><div style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:1px;color:#E05050;margin-bottom:8px">🎬 Bollywood Hook</div><p style="font-size:14px;line-height:1.7;color:var(--text2)">Think of the film <strong>Rang De Basanti</strong> — the students use Article 19(1)(a) (free speech) to expose corruption on radio. The government tries to shut them down — that's the reasonable restriction part! Free speech vs national security.</p></div></div>`,
  exam: `<div style="padding:16px"><div style="background:var(--surface);border:1px solid var(--border);border-radius:14px;padding:16px;margin-bottom:12px"><div style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:0.8px;color:var(--text3);margin-bottom:10px">🎓 Exam Angle</div><ul style="font-size:14px;line-height:1.7;color:var(--text2);padding-left:18px"><li>Article 19 applies only to <strong>citizens</strong> — NOT foreigners</li><li>Right to property 19(1)(f) was <strong>deleted by 44th Amendment 1978</strong></li><li>Press freedom is under 19(1)(a) — no separate article for it</li><li>Right to internet = part of 19(1)(a) per SC (Anuradha Bhasin case 2020)</li><li>Grounds for restriction differ for each freedom — memorise key ones</li></ul></div></div>`,
  laws: `<div style="padding:16px"><div style="border-left:2px solid var(--gold);padding:10px 0 10px 14px;margin-bottom:12px"><div style="font-size:13px;font-weight:600;color:var(--text)">Romesh Thappar v. State of Madras</div><div style="font-size:11px;color:var(--gold);font-weight:600">1950</div><div style="font-size:12px;color:var(--text2);margin-top:4px;line-height:1.5">First major case on free speech. SC struck down a law banning a journal — established that freedom of press is part of 19(1)(a).</div></div><div style="border-left:2px solid var(--gold);padding:10px 0 10px 14px;margin-bottom:12px"><div style="font-size:13px;font-weight:600;color:var(--text)">Shreya Singhal v. Union of India</div><div style="font-size:11px;color:var(--gold);font-weight:600">2015</div><div style="font-size:12px;color:var(--text2);margin-top:4px;line-height:1.5">SC struck down Section 66A of IT Act as unconstitutional — it violated Article 19(1)(a). Landmark case for internet freedom in India.</div></div></div>`,
  amend: `<div style="padding:16px"><div style="background:var(--surface);border:1px solid var(--border);border-radius:14px;padding:16px"><div style="display:flex;gap:10px;padding:10px 0;border-bottom:1px solid var(--border)"><span style="font-family:var(--font-mono);font-size:12px;font-weight:600;color:var(--accent);background:var(--accent-soft);padding:3px 8px;border-radius:8px;white-space:nowrap">1st Amendment, 1951</span><span style="font-size:13px;color:var(--text2)">Added "public order" as a ground for restricting free speech under 19(2)</span></div><div style="display:flex;gap:10px;padding:10px 0"><span style="font-family:var(--font-mono);font-size:12px;font-weight:600;color:var(--accent);background:var(--accent-soft);padding:3px 8px;border-radius:8px;white-space:nowrap">44th Amendment, 1978</span><span style="font-size:13px;color:var(--text2)">Deleted Article 19(1)(f) — right to property — most significant amendment to Article 19</span></div></div></div>`,
  trivia: `<div style="padding:16px"><div style="background:var(--surface);border:1px solid var(--border);border-radius:14px;padding:16px"><ul style="font-size:14px;line-height:1.9;color:var(--text2);padding-left:18px"><li>🗑️ The right to property (19(1)(f)) was removed during Indira Gandhi's government to facilitate land reforms and nationalisation</li><li>📱 Right to internet access was declared part of Article 19(1)(a) in the <strong>Anuradha Bhasin case (2020)</strong> — triggered by J&K internet shutdown</li><li>🎭 Right to silence (not speaking) is also part of 19(1)(a) — you cannot be forced to say something</li><li>🔢 Article 19 is only for citizens — this is why foreigners in India can be deported without invoking Article 19</li></ul></div></div>`,
  official: `<div style="padding:16px"><div style="font-family:var(--font-mono);font-size:13px;line-height:1.8;color:var(--text2);background:var(--bg2);border-radius:8px;padding:14px;border-left:3px solid var(--accent);margin-bottom:16px"><strong>Article 19(1). Protection of certain rights regarding freedom of speech, etc. —</strong><br><br>All citizens shall have the right—<br>(a) to freedom of speech and expression;<br>(b) to assemble peaceably and without arms;<br>(c) to form associations or unions or co-operative societies;<br>(d) to move freely throughout the territory of India;<br>(e) to reside and settle in any part of the territory of India;<br>(g) to practise any profession, or to carry on any occupation, trade or business.</div></div>`
},

"21": {
  explain: `<div style="padding:16px"><div style="background:var(--surface);border:1px solid var(--border);border-radius:14px;padding:16px;margin-bottom:12px"><div style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:0.8px;color:var(--text3);margin-bottom:10px">💡 Simple Explanation</div><p style="font-size:14px;line-height:1.7;color:var(--text2)">Article 21 is the <strong>most expansive Fundamental Right</strong>. It says no person shall be deprived of life or personal liberty except according to procedure established by law.</p><p style="font-size:14px;line-height:1.7;color:var(--text2);margin-top:8px">Through judicial interpretation, "right to life" now includes dozens of rights:</p><ul style="font-size:14px;line-height:1.7;color:var(--text2);padding-left:18px;margin-top:8px"><li>Right to live with dignity</li><li>Right to privacy (Puttaswamy 2017)</li><li>Right to health and medical care</li><li>Right to education (before 21-A)</li><li>Right to clean environment</li><li>Right to livelihood</li><li>Right to free legal aid</li></ul></div></div>`,
  memory: `<div style="padding:16px"><div style="background:linear-gradient(135deg,var(--accent-soft),var(--bg2));border:1px solid var(--accent);border-radius:14px;padding:16px;margin-bottom:12px"><div style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:1px;color:var(--accent);margin-bottom:10px">🧠 Memory Trick</div><p style="font-size:14px;line-height:1.7;color:var(--text);font-style:italic">"Article 21 = 21 is the age when life truly begins! Right to LIFE starts at 21. Like turning 21 — you get all the rights of a full life."</p></div><div style="background:linear-gradient(135deg,#FF6B6B15,#FFE66D15);border:1px solid #FF6B6B40;border-radius:14px;padding:14px"><div style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:1px;color:#E05050;margin-bottom:8px">🎬 Bollywood Hook</div><p style="font-size:14px;line-height:1.7;color:var(--text2)">The film <strong>Jolly LLB</strong> is literally about Article 21 — the right to fair trial, right to live with dignity. Every scene where the lawyer fights for the underdog is Article 21 in action!</p></div></div>`,
  exam: `<div style="padding:16px"><div style="background:var(--surface);border:1px solid var(--border);border-radius:14px;padding:16px;margin-bottom:12px"><div style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:0.8px;color:var(--text3);margin-bottom:10px">🎓 Exam Angle</div><ul style="font-size:14px;line-height:1.7;color:var(--text2);padding-left:18px"><li>Article 21 applies to BOTH citizens and foreigners</li><li>Cannot be suspended even during National Emergency (with Article 20)</li><li>Maneka Gandhi case (1978) — procedure must be just, fair, reasonable</li><li>Most expanded FR through judicial interpretation</li><li>Right to Privacy declared FR under Article 21 (Puttaswamy 2017)</li></ul></div></div>`,
  laws: `<div style="padding:16px"><div style="border-left:2px solid var(--gold);padding:10px 0 10px 14px;margin-bottom:12px"><div style="font-size:13px;font-weight:600;color:var(--text)">Maneka Gandhi v. Union of India</div><div style="font-size:11px;color:var(--gold);font-weight:600">1978</div><div style="font-size:12px;color:var(--text2);margin-top:4px;line-height:1.5">Overruled A.K. Gopalan. "Procedure established by law" must be just, fair and reasonable — not merely any procedure. Golden triangle of Arts 14, 19, 21.</div></div><div style="border-left:2px solid var(--gold);padding:10px 0 10px 14px;margin-bottom:12px"><div style="font-size:13px;font-weight:600;color:var(--text)">Justice K.S. Puttaswamy v. Union of India</div><div style="font-size:11px;color:var(--gold);font-weight:600">2017</div><div style="font-size:12px;color:var(--text2);margin-top:4px;line-height:1.5">9-judge bench unanimously declared Right to Privacy a FR under Article 21. One of the most significant constitutional judgments of the 21st century.</div></div><div style="border-left:2px solid var(--gold);padding:10px 0 10px 14px"><div style="font-size:13px;font-weight:600;color:var(--text)">Olga Tellis v. Bombay Municipal Corporation</div><div style="font-size:11px;color:var(--gold);font-weight:600">1985</div><div style="font-size:12px;color:var(--text2);margin-top:4px;line-height:1.5">Right to livelihood is part of Article 21 — evicting pavement dwellers without notice violates their right to life.</div></div></div>`,
  amend: `<div style="padding:16px"><div style="background:var(--surface);border:1px solid var(--border);border-radius:14px;padding:16px"><p style="font-size:14px;line-height:1.7;color:var(--text2)">Article 21 has <strong>never been directly amended</strong>. Its expansion has been entirely through judicial interpretation. The 44th Amendment (1978) made it non-suspendable even during Emergency — the most important indirect change.</p></div></div>`,
  trivia: `<div style="padding:16px"><div style="background:var(--surface);border:1px solid var(--border);border-radius:14px;padding:16px"><ul style="font-size:14px;line-height:1.9;color:var(--text2);padding-left:18px"><li>📜 Article 21 originally had a narrow meaning — A.K. Gopalan case (1950) said "procedure established by law" meant ANY law passed by Parliament</li><li>🔄 Maneka Gandhi case (1978) completely reversed this — now the procedure must be just and fair</li><li>🌍 India's Article 21 is now considered broader than the US 5th Amendment's "due process" clause</li><li>⚖️ The Supreme Court has derived 25+ rights from Article 21 through interpretation</li></ul></div></div>`,
  official: `<div style="padding:16px"><div style="font-family:var(--font-mono);font-size:13px;line-height:1.8;color:var(--text2);background:var(--bg2);border-radius:8px;padding:14px;border-left:3px solid var(--accent);margin-bottom:16px"><strong>Article 21. Protection of life and personal liberty —</strong><br><br>No person shall be deprived of his life or personal liberty except according to procedure established by law.</div><div style="background:var(--surface);border:1px solid var(--border);border-radius:14px;padding:14px"><p style="font-size:13px;line-height:1.7;color:var(--text2)">Despite being just one sentence, this is the most powerful article in the Constitution — courts have read into it the right to privacy, dignity, health, education, environment, livelihood, and much more.</p></div></div>`
},

"32": {
  explain: `<div style="padding:16px"><div style="background:var(--surface);border:1px solid var(--border);border-radius:14px;padding:16px;margin-bottom:12px"><div style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:0.8px;color:var(--text3);margin-bottom:10px">💡 Simple Explanation</div><p style="font-size:14px;line-height:1.7;color:var(--text2)">Article 32 is called the <strong>"Heart and Soul of the Constitution"</strong> by Dr. Ambedkar. It gives you the RIGHT to approach the Supreme Court directly if any Fundamental Right is violated.</p><p style="font-size:14px;line-height:1.7;color:var(--text2);margin-top:8px">The SC can issue 5 types of writs:</p><ul style="font-size:14px;line-height:1.7;color:var(--text2);padding-left:18px;margin-top:8px"><li><strong>Habeas Corpus</strong> — "Produce the body" — release from illegal detention</li><li><strong>Mandamus</strong> — "We command" — direct a public body to do its duty</li><li><strong>Prohibition</strong> — Stop lower court from exceeding jurisdiction</li><li><strong>Certiorari</strong> — Quash order of lower court</li><li><strong>Quo Warranto</strong> — "By what authority" — challenge illegal appointment</li></ul></div></div>`,
  memory: `<div style="padding:16px"><div style="background:linear-gradient(135deg,var(--accent-soft),var(--bg2));border:1px solid var(--accent);border-radius:14px;padding:16px;margin-bottom:12px"><div style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:1px;color:var(--accent);margin-bottom:10px">🧠 Memory Trick</div><p style="font-size:14px;line-height:1.7;color:var(--text);font-style:italic">"Writs = <strong>HMPCQ</strong> — <strong>H</strong>ow <strong>M</strong>any <strong>P</strong>eople <strong>C</strong>ome to <strong>Q</strong>ourt? Habeas Corpus, Mandamus, Prohibition, Certiorari, Quo Warranto!"</p></div><div style="background:linear-gradient(135deg,#FF6B6B15,#FFE66D15);border:1px solid #FF6B6B40;border-radius:14px;padding:14px"><div style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:1px;color:#E05050;margin-bottom:8px">🎬 Bollywood Hook</div><p style="font-size:14px;line-height:1.7;color:var(--text2)">Article 32 is like the <strong>final boss level</strong> in a game — when all else fails, you go DIRECTLY to the Supreme Court! Like in Bollywood when the hero finally reaches the High Command. "Seedha Supreme Court!"</p></div></div>`,
  exam: `<div style="padding:16px"><div style="background:var(--surface);border:1px solid var(--border);border-radius:14px;padding:16px;margin-bottom:12px"><div style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:0.8px;color:var(--text3);margin-bottom:10px">🎓 Exam Angle</div><ul style="font-size:14px;line-height:1.7;color:var(--text2);padding-left:18px"><li>Article 32 = SC only | Article 226 = HC (wider jurisdiction)</li><li>Article 32 itself is a Fundamental Right — cannot be suspended except during Emergency</li><li>SC CANNOT refuse to issue writ if FR is violated — it is a <strong>guaranteed right</strong></li><li>Article 32 can be suspended during National Emergency under Article 359 (EXCEPT Articles 20 and 21)</li></ul></div></div>`,
  laws: `<div style="padding:16px"><div style="border-left:2px solid var(--gold);padding:10px 0 10px 14px;margin-bottom:12px"><div style="font-size:13px;font-weight:600;color:var(--text)">Romesh Thappar v. State of Madras</div><div style="font-size:11px;color:var(--gold);font-weight:600">1950</div><div style="font-size:12px;color:var(--text2);margin-top:4px;line-height:1.5">SC held it has wide powers under Article 32 to protect FRs. Established the court as the "sentinel on the qui vive" for fundamental rights.</div></div><div style="border-left:2px solid var(--gold);padding:10px 0 10px 14px"><div style="font-size:13px;font-weight:600;color:var(--text)">Daryao v. State of UP</div><div style="font-size:11px;color:var(--gold);font-weight:600">1961</div><div style="font-size:12px;color:var(--text2);margin-top:4px;line-height:1.5">If a petition under Article 226 (HC) is dismissed, the same petition under Article 32 (SC) is barred by res judicata — established procedural limits.</div></div></div>`,
  amend: `<div style="padding:16px"><div style="background:var(--surface);border:1px solid var(--border);border-radius:14px;padding:16px"><p style="font-size:14px;line-height:1.7;color:var(--text2)">Article 32 has <strong>never been amended</strong>. The 44th Amendment (1978) added a safeguard — Article 32 cannot be suspended even during National Emergency under Article 359, but ONLY for Articles 20 and 21. For other FRs, Article 32 can technically be suspended during Emergency.</p></div></div>`,
  trivia: `<div style="padding:16px"><div style="background:var(--surface);border:1px solid var(--border);border-radius:14px;padding:16px"><ul style="font-size:14px;line-height:1.9;color:var(--text2);padding-left:18px"><li>💬 Dr. Ambedkar called Article 32 <strong>"the most important article of the Constitution — without it, the Constitution is null and void"</strong></li><li>📊 The SC receives over <strong>60,000 petitions annually</strong> under Article 32 — it's the most used article in litigation</li><li>🆚 Article 32 vs 226: HC under 226 can issue writs for ANY purpose; SC under 32 only for FR violations — but SC's jurisdiction is wider geographically</li><li>⚖️ Public Interest Litigation (PIL) grew out of a liberal interpretation of Article 32 by Justice P.N. Bhagwati in the 1980s</li></ul></div></div>`,
  official: `<div style="padding:16px"><div style="font-family:var(--font-mono);font-size:13px;line-height:1.8;color:var(--text2);background:var(--bg2);border-radius:8px;padding:14px;border-left:3px solid var(--accent);margin-bottom:16px"><strong>Article 32. Remedies for enforcement of rights conferred by this Part —</strong><br><br>(1) The right to move the Supreme Court by appropriate proceedings for the enforcement of the rights conferred by this Part is guaranteed.<br><br>(2) The Supreme Court shall have power to issue directions or orders or writs, including writs in the nature of habeas corpus, mandamus, prohibition, quo warranto and certiorari, whichever may be appropriate, for the enforcement of any of the rights conferred by this Part.</div></div>`
},

"44": {
  explain: `<div style="padding:16px"><div style="background:var(--surface);border:1px solid var(--border);border-radius:14px;padding:16px;margin-bottom:12px"><div style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:0.8px;color:var(--text3);margin-bottom:10px">💡 Simple Explanation</div><p style="font-size:14px;line-height:1.7;color:var(--text2)">Article 44 directs the State to secure a <strong>Uniform Civil Code (UCC)</strong> for all citizens — one set of personal laws governing marriage, divorce, inheritance for everyone regardless of religion.</p><p style="font-size:14px;line-height:1.7;color:var(--text2);margin-top:8px">Currently India has different personal laws: Hindu Marriage Act, Muslim Personal Law (Shariat), Christian Marriage Act etc. UCC would replace all of these with one common law.</p><p style="font-size:14px;line-height:1.7;color:var(--text2);margin-top:8px">⚠️ It's a <strong>DPSP</strong> — non-justiciable, just a directive to the State.</p></div></div>`,
  memory: `<div style="padding:16px"><div style="background:linear-gradient(135deg,var(--accent-soft),var(--bg2));border:1px solid var(--accent);border-radius:14px;padding:16px;margin-bottom:12px"><div style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:1px;color:var(--accent);margin-bottom:10px">🧠 Memory Trick</div><p style="font-size:14px;line-height:1.7;color:var(--text);font-style:italic">"Article <strong>44</strong> = <strong>4</strong> religions, <strong>4</strong>ever one code. 44 = double 4 = double the debate! UCC has been debated for decades!"</p></div><div style="background:linear-gradient(135deg,#FF6B6B15,#FFE66D15);border:1px solid #FF6B6B40;border-radius:14px;padding:14px"><div style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:1px;color:#E05050;margin-bottom:8px">🎬 Bollywood Hook</div><p style="font-size:14px;line-height:1.7;color:var(--text2)">Think of Shah Bano case — a Muslim woman's divorce case that went to the Supreme Court. The SC said UCC should be implemented. The controversy that followed is Article 44 in real life — one of India's most politically charged constitutional provisions!</p></div></div>`,
  exam: `<div style="padding:16px"><div style="background:var(--surface);border:1px solid var(--border);border-radius:14px;padding:16px;margin-bottom:12px"><div style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:0.8px;color:var(--text3);margin-bottom:10px">🎓 Exam Angle</div><ul style="font-size:14px;line-height:1.7;color:var(--text2);padding-left:18px"><li>Article 44 is a <strong>DPSP</strong> — Part IV, non-justiciable</li><li>Goa is the only state with a <strong>common civil code</strong></li><li>SC has repeatedly asked Parliament to implement UCC: Shah Bano (1985), Sarla Mudgal (1995), Shayara Bano (2017)</li><li>Uttarakhand became the first state to pass UCC legislation in 2024</li></ul></div></div>`,
  laws: `<div style="padding:16px"><div style="border-left:2px solid var(--gold);padding:10px 0 10px 14px;margin-bottom:12px"><div style="font-size:13px;font-weight:600;color:var(--text)">Mohd. Ahmed Khan v. Shah Bano Begum</div><div style="font-size:11px;color:var(--gold);font-weight:600">1985</div><div style="font-size:12px;color:var(--text2);margin-top:4px;line-height:1.5">SC upheld maintenance rights of divorced Muslim woman. Strongly recommended implementation of UCC. Led to controversy and Muslim Women (Protection) Act 1986.</div></div><div style="border-left:2px solid var(--gold);padding:10px 0 10px 14px"><div style="font-size:13px;font-weight:600;color:var(--text)">Sarla Mudgal v. Union of India</div><div style="font-size:11px;color:var(--gold);font-weight:600">1995</div><div style="font-size:12px;color:var(--text2);margin-top:4px;line-height:1.5">Held that conversion to Islam for purpose of second marriage is void. Again called for UCC implementation. UCC remains unimplemented at the national level.</div></div></div>`,
  amend: `<div style="padding:16px"><div style="background:var(--surface);border:1px solid var(--border);border-radius:14px;padding:16px"><p style="font-size:14px;line-height:1.7;color:var(--text2)">Article 44 has <strong>never been amended</strong>. The political sensitivity of UCC has meant Parliament has avoided both implementing it and changing the article.</p></div></div>`,
  trivia: `<div style="padding:16px"><div style="background:var(--surface);border:1px solid var(--border);border-radius:14px;padding:16px"><ul style="font-size:14px;line-height:1.9;color:var(--text2);padding-left:18px"><li>🏛️ <strong>Goa's civil code</strong> (Portuguese Civil Code of 1867) is often cited as a model for UCC — it applies to all Goans regardless of religion</li><li>📅 The Law Commission of India has examined UCC multiple times — its 2018 report said UCC is "neither necessary nor desirable at this stage"</li><li>🗺️ <strong>Uttarakhand</strong> became the first Indian state to enact a UCC in 2024</li><li>💬 Dr. Ambedkar supported UCC; many Muslim League members opposed it during Constituent Assembly debates</li></ul></div></div>`,
  official: `<div style="padding:16px"><div style="font-family:var(--font-mono);font-size:13px;line-height:1.8;color:var(--text2);background:var(--bg2);border-radius:8px;padding:14px;border-left:3px solid var(--accent);margin-bottom:16px"><strong>Article 44. Uniform civil code for the citizens —</strong><br><br>The State shall endeavour to secure for the citizens a uniform civil code throughout the territory of India.</div><div style="background:var(--surface);border:1px solid var(--border);border-radius:14px;padding:14px"><p style="font-size:13px;line-height:1.7;color:var(--text2)">Just one sentence — but one of the most debated sentences in the entire Constitution. The State must "endeavour" (try) — it's a directive, not a command.</p></div></div>`
},

"51A": {
  explain: `<div style="padding:16px"><div style="background:var(--surface);border:1px solid var(--border);border-radius:14px;padding:16px;margin-bottom:12px"><div style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:0.8px;color:var(--text3);margin-bottom:10px">💡 Simple Explanation</div><p style="font-size:14px;line-height:1.7;color:var(--text2)">Article 51-A contains <strong>11 Fundamental Duties</strong> — obligations of every citizen towards the nation. They are non-justiciable (courts can't enforce them) but morally binding.</p><p style="font-size:14px;line-height:1.7;color:var(--text2);margin-top:8px"><strong>11 Duties (key ones):</strong></p><ul style="font-size:14px;line-height:1.7;color:var(--text2);padding-left:18px;margin-top:4px"><li>(a) Abide by the Constitution and respect national symbols</li><li>(b) Cherish noble ideals of freedom struggle</li><li>(c) Uphold sovereignty and integrity of India</li><li>(e) Promote harmony among all citizens</li><li>(g) Protect natural environment</li><li>(h) Develop scientific temper</li><li>(j) Strive for excellence</li><li>(k) Provide education to children aged 6-14 (11th duty)</li></ul></div></div>`,
  memory: `<div style="padding:16px"><div style="background:linear-gradient(135deg,var(--accent-soft),var(--bg2));border:1px solid var(--accent);border-radius:14px;padding:16px;margin-bottom:12px"><div style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:1px;color:var(--accent);margin-bottom:10px">🧠 Memory Trick</div><p style="font-size:14px;line-height:1.7;color:var(--text);font-style:italic">"<strong>51A</strong> = <strong>51</strong> stars on no flag, but <strong>A</strong>ll citizens have duties. Added in 1976 — during Emergency — inspired by USSR Constitution's citizen duties."</p></div><div style="background:linear-gradient(135deg,#FF6B6B15,#FFE66D15);border:1px solid #FF6B6B40;border-radius:14px;padding:14px"><div style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:1px;color:#E05050;margin-bottom:8px">🎬 Bollywood Hook</div><p style="font-size:14px;line-height:1.7;color:var(--text2)">Remember <strong>Lagaan</strong> — the whole village comes together for a common cause? That's Article 51-A(e) — promote harmony and spirit of brotherhood. Every duty in 51-A is essentially asking citizens to be that village in Lagaan!</p></div></div>`,
  exam: `<div style="padding:16px"><div style="background:var(--surface);border:1px solid var(--border);border-radius:14px;padding:16px;margin-bottom:12px"><div style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:0.8px;color:var(--text3);margin-bottom:10px">🎓 Exam Angle</div><ul style="font-size:14px;line-height:1.7;color:var(--text2);padding-left:18px"><li>Added by <strong>42nd Amendment 1976</strong> (10 duties) — during Emergency, inspired by USSR</li><li>11th duty added by <strong>86th Amendment 2002</strong></li><li>Based on <strong>Swaran Singh Committee</strong> recommendations (1976)</li><li>Non-justiciable but courts use them to interpret laws</li><li>Total: <strong>11 duties</strong> — classic BPSC trap (students say 10)</li></ul></div></div>`,
  laws: `<div style="padding:16px"><div style="border-left:2px solid var(--gold);padding:10px 0 10px 14px;margin-bottom:12px"><div style="font-size:13px;font-weight:600;color:var(--text)">AIIMS Students' Union v. AIIMS</div><div style="font-size:11px;color:var(--gold);font-weight:600">2002</div><div style="font-size:12px;color:var(--text2);margin-top:4px;line-height:1.5">SC held that Fundamental Duties can be used as an aid to interpret constitutional and legal provisions. They are not empty words.</div></div><div style="border-left:2px solid var(--gold);padding:10px 0 10px 14px"><div style="font-size:13px;font-weight:600;color:var(--text)">Vishaka v. State of Rajasthan</div><div style="font-size:11px;color:var(--gold);font-weight:600">1997</div><div style="font-size:12px;color:var(--text2);margin-top:4px;line-height:1.5">SC used Fundamental Duties (51-A(e) and (f)) alongside international law to lay down guidelines against sexual harassment at workplace.</div></div></div>`,
  amend: `<div style="padding:16px"><div style="background:var(--surface);border:1px solid var(--border);border-radius:14px;padding:16px"><div style="display:flex;gap:10px;padding:10px 0;border-bottom:1px solid var(--border)"><span style="font-family:var(--font-mono);font-size:12px;font-weight:600;color:var(--accent);background:var(--accent-soft);padding:3px 8px;border-radius:8px;white-space:nowrap">42nd Amendment, 1976</span><span style="font-size:13px;color:var(--text2)">Inserted Article 51-A with 10 Fundamental Duties — added Part IVA to the Constitution</span></div><div style="display:flex;gap:10px;padding:10px 0"><span style="font-family:var(--font-mono);font-size:12px;font-weight:600;color:var(--accent);background:var(--accent-soft);padding:3px 8px;border-radius:8px;white-space:nowrap">86th Amendment, 2002</span><span style="font-size:13px;color:var(--text2)">Added the 11th duty — parents/guardians must provide education to children aged 6-14</span></div></div></div>`,
  trivia: `<div style="padding:16px"><div style="background:var(--surface);border:1px solid var(--border);border-radius:14px;padding:16px"><ul style="font-size:14px;line-height:1.9;color:var(--text2);padding-left:18px"><li>🇷🇺 Fundamental Duties were <strong>inspired by the Soviet (USSR) Constitution</strong> — the only major influence from a communist country</li><li>📋 The <strong>Swaran Singh Committee (1976)</strong> recommended Fundamental Duties — Indira Gandhi's government added them during Emergency</li><li>🎯 Japan and Russia have Fundamental Duties in their constitutions — but most Western democracies don't</li><li>⚠️ Critics called them "Emergency relics" — added when democracy was suspended, by an undemocratic process</li></ul></div></div>`,
  official: `<div style="padding:16px"><div style="font-family:var(--font-mono);font-size:13px;line-height:1.8;color:var(--text2);background:var(--bg2);border-radius:8px;padding:14px;border-left:3px solid var(--accent);margin-bottom:16px"><strong>Article 51A. Fundamental duties —</strong><br><br>It shall be the duty of every citizen of India—<br>(a) to abide by the Constitution and respect its ideals and institutions, the National Flag and the National Anthem;<br>(b) to cherish and follow the noble ideals which inspired our national struggle for freedom;<br>(c) to uphold and protect the sovereignty, unity and integrity of India;<br>...(and 8 more duties)<br>(k) who is a parent or guardian to provide opportunities for education to his child or, as the case may be, ward between the age of six and fourteen years. [Added by 86th Amendment]</div></div>`
},

"52": {
  explain: `<div style="padding:16px"><div style="background:var(--surface);border:1px solid var(--border);border-radius:14px;padding:16px;margin-bottom:12px"><div style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:0.8px;color:var(--text3);margin-bottom:10px">💡 Simple Explanation</div><p style="font-size:14px;line-height:1.7;color:var(--text2)">Article 52 simply establishes that <strong>there shall be a President of India</strong>. The President is the <strong>constitutional head</strong> of the Union — the formal head, not the real executive.</p><p style="font-size:14px;line-height:1.7;color:var(--text2);margin-top:8px">India follows the <strong>Westminster model</strong>: President = nominal head (like UK's King), Prime Minister = real head. The President acts on the <strong>aid and advice</strong> of the Council of Ministers (Article 74).</p></div></div>`,
  memory: `<div style="padding:16px"><div style="background:linear-gradient(135deg,var(--accent-soft),var(--bg2));border:1px solid var(--accent);border-radius:14px;padding:16px"><div style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:1px;color:var(--accent);margin-bottom:10px">🧠 Memory Trick</div><p style="font-size:14px;line-height:1.7;color:var(--text);font-style:italic">"Article 52 = <strong>5 + 2 = 7</strong>. Rashtrapati Bhavan has 7 floors! Article 52 creates the President who lives there. Or simply: Article 52 = President of India's birthday number!"</p></div></div>`,
  exam: `<div style="padding:16px"><div style="background:var(--surface);border:1px solid var(--border);border-radius:14px;padding:16px"><ul style="font-size:14px;line-height:1.7;color:var(--text2);padding-left:18px"><li>President = constitutional head (Article 52, 53)</li><li>Real executive power = PM + Cabinet (Article 74)</li><li>Election — indirect, by elected members of Parliament + State Assemblies (Article 54)</li><li>Minimum age = 35 years</li><li>Term = 5 years, eligible for re-election</li><li>Qualification: must be eligible to be Lok Sabha member</li></ul></div></div>`,
  laws: `<div style="padding:16px"><div style="border-left:2px solid var(--gold);padding:10px 0 10px 14px"><div style="font-size:13px;font-weight:600;color:var(--text)">Rameshwar Prasad v. Union of India</div><div style="font-size:11px;color:var(--gold);font-weight:600">2006</div><div style="font-size:12px;color:var(--text2);margin-top:4px;line-height:1.5">SC held that President's action of dissolving Bihar assembly was unconstitutional — established that President cannot act arbitrarily and must act on CoM advice.</div></div></div>`,
  amend: `<div style="padding:16px"><div style="background:var(--surface);border:1px solid var(--border);border-radius:14px;padding:16px"><p style="font-size:14px;line-height:1.7;color:var(--text2)">Article 52 has <strong>never been amended</strong>. However, the <strong>42nd Amendment (1976)</strong> made it clear that the President must act on the advice of the Cabinet, and the <strong>44th Amendment (1978)</strong> added that the President can send back advice once for reconsideration.</p></div></div>`,
  trivia: `<div style="padding:16px"><div style="background:var(--surface);border:1px solid var(--border);border-radius:14px;padding:16px"><ul style="font-size:14px;line-height:1.9;color:var(--text2);padding-left:18px"><li>🏛️ India has had 15 Presidents so far — Dr. Rajendra Prasad was the first (1950-1962), serving the longest</li><li>👩 Pratibha Patil (2007-2012) was India's first female President</li><li>🔬 Dr. A.P.J. Abdul Kalam (2002-2007) is called the "People's President" — scientists as President!</li><li>📍 Rashtrapati Bhavan was originally built for the British Viceroy — it has 340 rooms</li></ul></div></div>`,
  official: `<div style="padding:16px"><div style="font-family:var(--font-mono);font-size:13px;line-height:1.8;color:var(--text2);background:var(--bg2);border-radius:8px;padding:14px;border-left:3px solid var(--accent)"><strong>Article 52. The President of India —</strong><br><br>There shall be a President of India.</div></div>`
},

"110": {
  explain: `<div style="padding:16px"><div style="background:var(--surface);border:1px solid var(--border);border-radius:14px;padding:16px;margin-bottom:12px"><div style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:0.8px;color:var(--text3);margin-bottom:10px">💡 Simple Explanation</div><p style="font-size:14px;line-height:1.7;color:var(--text2)">Article 110 defines what a <strong>Money Bill</strong> is — arguably the most politically important definition in the Constitution.</p><p style="font-size:14px;line-height:1.7;color:var(--text2);margin-top:8px">A bill is a Money Bill if it deals with:</p><ul style="font-size:14px;line-height:1.7;color:var(--text2);padding-left:18px;margin-top:4px"><li>Imposition, abolition, remission, alteration of any tax</li><li>Borrowing of money by the government</li><li>Custody of the Consolidated Fund of India</li><li>Appropriation of moneys from the Consolidated Fund</li><li>Declaration of any expenditure as charged</li><li>Receipt of money on account of the CFI</li><li>Any matter incidental to the above</li></ul><p style="font-size:14px;line-height:1.7;color:var(--text2);margin-top:8px">🔑 <strong>Key: Speaker of Lok Sabha certifies</strong> whether a bill is a Money Bill.</p></div></div>`,
  memory: `<div style="padding:16px"><div style="background:linear-gradient(135deg,var(--accent-soft),var(--bg2));border:1px solid var(--accent);border-radius:14px;padding:16px;margin-bottom:12px"><div style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:1px;color:var(--accent);margin-bottom:10px">🧠 Memory Trick</div><p style="font-size:14px;line-height:1.7;color:var(--text);font-style:italic">"Article <strong>110</strong> = <strong>₹110</strong> — all about money! Where there's rupees, there's Article 110. Money Bill = 110. Period."</p></div><div style="background:linear-gradient(135deg,#FF6B6B15,#FFE66D15);border:1px solid #FF6B6B40;border-radius:14px;padding:14px"><div style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:1px;color:#E05050;margin-bottom:8px">🎬 Bollywood Hook</div><p style="font-size:14px;line-height:1.7;color:var(--text2)">Rajya Sabha is like that rich uncle who wants to have a say in how money is spent — but the Constitution (Article 110) says NOPE! Money Bills are Lok Sabha's domain. Rajya Sabha can only suggest, not decide. "Paise ki baat toh Lok Sabha karega!"</p></div></div>`,
  exam: `<div style="padding:16px"><div style="background:var(--surface);border:1px solid var(--border);border-radius:14px;padding:16px;margin-bottom:12px"><div style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:0.8px;color:var(--text3);margin-bottom:10px">🎓 Exam Angle</div><ul style="font-size:14px;line-height:1.7;color:var(--text2);padding-left:18px"><li>Money Bills can ONLY be introduced in <strong>Lok Sabha</strong></li><li>Rajya Sabha can only suggest amendments — Lok Sabha can <strong>accept or reject</strong></li><li>If Rajya Sabha doesn't act within <strong>14 days</strong>, bill is deemed passed</li><li>Speaker's certificate is <strong>final and conclusive</strong> — cannot be challenged in court (Article 122)</li><li>Aadhaar Act controversy — 2016, Aadhaar was passed as Money Bill — challenged but upheld</li></ul></div></div>`,
  laws: `<div style="padding:16px"><div style="border-left:2px solid var(--gold);padding:10px 0 10px 14px;margin-bottom:12px"><div style="font-size:13px;font-weight:600;color:var(--text)">Mohd. Saeed Siddiqui v. State of UP</div><div style="font-size:11px;color:var(--gold);font-weight:600">2014</div><div style="font-size:12px;color:var(--text2);margin-top:4px;line-height:1.5">Discussed the scope of Speaker's power under Article 110 to certify Money Bills — established limits on judicial review of the Speaker's certification.</div></div><div style="border-left:2px solid var(--gold);padding:10px 0 10px 14px"><div style="font-size:13px;font-weight:600;color:var(--text)">Rojer Mathew v. South Indian Bank</div><div style="font-size:11px;color:var(--gold);font-weight:600">2019</div><div style="font-size:12px;color:var(--text2);margin-top:4px;line-height:1.5">5-judge bench referred to a larger bench whether Finance Acts passed as Money Bills (amending other laws) are constitutional. Major pending question.</div></div></div>`,
  amend: `<div style="padding:16px"><div style="background:var(--surface);border:1px solid var(--border);border-radius:14px;padding:16px"><p style="font-size:14px;line-height:1.7;color:var(--text2)">Article 110 has <strong>never been directly amended</strong>. However, its interpretation has evolved — the controversy over Aadhaar Act (2016) being passed as a Money Bill despite having non-financial provisions tested its limits.</p></div></div>`,
  trivia: `<div style="padding:16px"><div style="background:var(--surface);border:1px solid var(--border);border-radius:14px;padding:16px"><ul style="font-size:14px;line-height:1.9;color:var(--text2);padding-left:18px"><li>💳 The <strong>Aadhaar Act 2016</strong> was passed as a Money Bill — allowing it to bypass Rajya Sabha where the government lacked majority. Major constitutional controversy!</li><li>🏦 Finance Bills (Budget implementation) are Money Bills — the annual budget speech leads to Money Bills</li><li>🔢 The distinction matters because Rajya Sabha cannot block Money Bills — making it a political tool</li><li>⚖️ The Speaker's certificate on Money Bills is final — courts have largely refused to interfere</li></ul></div></div>`,
  official: `<div style="padding:16px"><div style="font-family:var(--font-mono);font-size:13px;line-height:1.8;color:var(--text2);background:var(--bg2);border-radius:8px;padding:14px;border-left:3px solid var(--accent)"><strong>Article 110. Definition of "Money Bills" —</strong><br><br>(1) For the purposes of this Chapter, a Bill shall be deemed to be a Money Bill if it contains only provisions dealing with all or any of the following matters, namely:—<br>(a) the imposition, abolition, remission, alteration or regulation of any tax;<br>(b) the regulation of the borrowing of money or the giving of any guarantee by the Government of India...<br><br>(3) If any question arises whether a Bill is a Money Bill or not, the decision of the Speaker of the House of the People thereon shall be final.</div></div>`
},

"352": {
  explain: `<div style="padding:16px"><div style="background:var(--surface);border:1px solid var(--border);border-radius:14px;padding:16px;margin-bottom:12px"><div style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:0.8px;color:var(--text3);margin-bottom:10px">💡 Simple Explanation</div><p style="font-size:14px;line-height:1.7;color:var(--text2)">Article 352 allows the President to proclaim <strong>National Emergency</strong> — the most powerful provision in the Constitution. It effectively converts India's federal structure into a unitary one.</p><p style="font-size:14px;line-height:1.7;color:var(--text2);margin-top:8px"><strong>Grounds:</strong></p><ul style="font-size:14px;line-height:1.7;color:var(--text2);padding-left:18px;margin-top:4px"><li>War</li><li>External Aggression</li><li>Armed Rebellion (changed from "internal disturbance" by 44th Amendment)</li></ul><p style="font-size:14px;line-height:1.7;color:var(--text2);margin-top:8px"><strong>3 times used:</strong> 1962 (China war), 1971 (Pakistan war), 1975-77 (Internal emergency — most controversial)</p></div></div>`,
  memory: `<div style="padding:16px"><div style="background:linear-gradient(135deg,var(--accent-soft),var(--bg2));border:1px solid var(--accent);border-radius:14px;padding:16px;margin-bottom:12px"><div style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:1px;color:var(--accent);margin-bottom:10px">🧠 Memory Trick</div><p style="font-size:14px;line-height:1.7;color:var(--text);font-style:italic">"Article <strong>352</strong> = <strong>3</strong> types of emergency, <strong>5</strong> effects, <strong>2</strong> years maximum without renewal. 3-5-2 = 352! National Emergency."</p></div><div style="background:linear-gradient(135deg,#FF6B6B15,#FFE66D15);border:1px solid #FF6B6B40;border-radius:14px;padding:14px"><div style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:1px;color:#E05050;margin-bottom:8px">🎬 Bollywood Hook</div><p style="font-size:14px;line-height:1.7;color:var(--text2)">The film <strong>Indu Sarkar (2017)</strong> is set during the 1975 Emergency — when Indira Gandhi used Article 352 to suspend democracy. Press was censored, opposition leaders jailed. That's what Article 352 can do in the wrong hands!</p></div></div>`,
  exam: `<div style="padding:16px"><div style="background:var(--surface);border:1px solid var(--border);border-radius:14px;padding:16px;margin-bottom:12px"><div style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:0.8px;color:var(--text3);margin-bottom:10px">🎓 Exam Angle</div><ul style="font-size:14px;line-height:1.7;color:var(--text2);padding-left:18px"><li>President proclaims on <strong>written advice of Cabinet</strong> (44th Amendment requirement)</li><li>Approved by Parliament within <strong>one month</strong> by special majority</li><li>Lok Sabha can revoke by simple majority (44th Amendment)</li><li>FRs under Articles 19 suspended automatically; 20 & 21 CANNOT be suspended</li><li>Lok Sabha term can be extended during emergency</li></ul></div></div>`,
  laws: `<div style="padding:16px"><div style="border-left:2px solid var(--gold);padding:10px 0 10px 14px;margin-bottom:12px"><div style="font-size:13px;font-weight:600;color:var(--text)">A.D.M. Jabalpur v. Shivkant Shukla</div><div style="font-size:11px;color:var(--gold);font-weight:600">1976</div><div style="font-size:12px;color:var(--text2);margin-top:4px;line-height:1.5">"Habeas Corpus case" — SC shamefully held that during Emergency, courts cannot examine detention orders. One of SC's worst judgments, later overruled.</div></div><div style="border-left:2px solid var(--gold);padding:10px 0 10px 14px"><div style="font-size:13px;font-weight:600;color:var(--text)">Minerva Mills v. Union of India</div><div style="font-size:11px;color:var(--gold);font-weight:600">1980</div><div style="font-size:12px;color:var(--text2);margin-top:4px;line-height:1.5">Post-Emergency, SC struck down 42nd Amendment provisions that made Emergency immune from judicial review. Restored checks and balances.</div></div></div>`,
  amend: `<div style="padding:16px"><div style="background:var(--surface);border:1px solid var(--border);border-radius:14px;padding:16px"><div style="display:flex;gap:10px;padding:10px 0"><span style="font-family:var(--font-mono);font-size:12px;font-weight:600;color:var(--accent);background:var(--accent-soft);padding:3px 8px;border-radius:8px;white-space:nowrap">44th Amendment, 1978</span><span style="font-size:13px;color:var(--text2)">Most important changes: (1) "Armed rebellion" replaced "internal disturbance"; (2) Cabinet must give written advice; (3) Lok Sabha can revoke by simple majority; (4) Re-approval needed every 6 months</span></div></div></div>`,
  trivia: `<div style="padding:16px"><div style="background:var(--surface);border:1px solid var(--border);border-radius:14px;padding:16px"><ul style="font-size:14px;line-height:1.9;color:var(--text2);padding-left:18px"><li>📅 The 1975 Emergency (25 June 1975 to 21 March 1977) is called the <strong>darkest period of Indian democracy</strong></li><li>🗞️ During 1975 Emergency: press censored, 21-month democracy suspension, over 1 lakh people detained without trial</li><li>🗳️ Indira Gandhi called elections in 1977 thinking she would win — lost badly. The Emergency ended.</li><li>📋 The <strong>Shah Commission</strong> was set up after Emergency to investigate its excesses</li></ul></div></div>`,
  official: `<div style="padding:16px"><div style="font-family:var(--font-mono);font-size:13px;line-height:1.8;color:var(--text2);background:var(--bg2);border-radius:8px;padding:14px;border-left:3px solid var(--accent)"><strong>Article 352. Proclamation of Emergency —</strong><br><br>(1) If the President is satisfied that a grave emergency exists whereby the security of India or of any part of the territory thereof is threatened, whether by war or external aggression or armed rebellion, the President may, by Proclamation, make a declaration to that effect in respect of the whole of India or of such part of the territory thereof as may be specified in the Proclamation.</div></div>`
},

"368": {
  explain: `<div style="padding:16px"><div style="background:var(--surface);border:1px solid var(--border);border-radius:14px;padding:16px;margin-bottom:12px"><div style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:0.8px;color:var(--text3);margin-bottom:10px">💡 Simple Explanation</div><p style="font-size:14px;line-height:1.7;color:var(--text2)">Article 368 gives Parliament the power to <strong>amend the Constitution</strong>. But after the Kesavananda Bharati case (1973), Parliament cannot use Article 368 to destroy the <strong>Basic Structure</strong> of the Constitution.</p><p style="font-size:14px;line-height:1.7;color:var(--text2);margin-top:8px"><strong>Three types of amendment procedures:</strong></p><ul style="font-size:14px;line-height:1.7;color:var(--text2);padding-left:18px;margin-top:4px"><li><strong>Simple majority</strong> — Ordinary bills (not Article 368)</li><li><strong>Special majority</strong> — 2/3 of members present + voting AND majority of total membership</li><li><strong>Special majority + State ratification</strong> — Federal provisions (half the states must ratify)</li></ul></div></div>`,
  memory: `<div style="padding:16px"><div style="background:linear-gradient(135deg,var(--accent-soft),var(--bg2));border:1px solid var(--accent);border-radius:14px;padding:16px;margin-bottom:12px"><div style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:1px;color:var(--accent);margin-bottom:10px">🧠 Memory Trick</div><p style="font-size:14px;line-height:1.7;color:var(--text);font-style:italic">"Article <strong>368</strong> = <strong>3</strong>68 = Parliament can do <strong>3</strong> things: Simple, Special, Special+States. Like a <strong>3</strong>-level video game boss — each level harder to beat!"</p></div><div style="background:linear-gradient(135deg,#FF6B6B15,#FFE66D15);border:1px solid #FF6B6B40;border-radius:14px;padding:14px"><div style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:1px;color:#E05050;margin-bottom:8px">🎬 Bollywood Hook</div><p style="font-size:14px;line-height:1.7;color:var(--text2)">Imagine the Constitution as a superhero's suit — you can upgrade parts of it (Article 368), but you can't remove the core superpower (Basic Structure). Like Tony Stark upgrading Iron Man's suit but keeping the arc reactor — that's the Basic Structure doctrine!</p></div></div>`,
  exam: `<div style="padding:16px"><div style="background:var(--surface);border:1px solid var(--border);border-radius:14px;padding:16px;margin-bottom:12px"><div style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:0.8px;color:var(--text3);margin-bottom:10px">🎓 Exam Angle</div><ul style="font-size:14px;line-height:1.7;color:var(--text2);padding-left:18px"><li>Special majority = 2/3 of members present + voting AND majority of TOTAL membership</li><li>India has the most amended constitution — <strong>106 amendments</strong> as of 2023</li><li>Basic Structure cannot be amended — Kesavananda Bharati 1973</li><li>President cannot withhold assent to Amendment Bills (Article 368(2))</li><li>No joint sitting for amendment bills — unlike ordinary bills</li></ul></div></div>`,
  laws: `<div style="padding:16px"><div style="border-left:2px solid var(--gold);padding:10px 0 10px 14px;margin-bottom:12px"><div style="font-size:13px;font-weight:600;color:var(--text)">Kesavananda Bharati v. State of Kerala</div><div style="font-size:11px;color:var(--gold);font-weight:600">1973</div><div style="font-size:12px;color:var(--text2);margin-top:4px;line-height:1.5">13-judge bench (largest ever) propounded the Basic Structure Doctrine — Parliament can amend any part of Constitution but cannot destroy its basic structure. Most important constitutional case ever.</div></div><div style="border-left:2px solid var(--gold);padding:10px 0 10px 14px"><div style="font-size:13px;font-weight:600;color:var(--text)">Indira Nehru Gandhi v. Raj Narain</div><div style="font-size:11px;color:var(--gold);font-weight:600">1975</div><div style="font-size:12px;color:var(--text2);margin-top:4px;line-height:1.5">Applied Basic Structure doctrine to strike down 39th Amendment that had immunized PM's election from judicial review. Free and fair elections = Basic Structure.</div></div></div>`,
  amend: `<div style="padding:16px"><div style="background:var(--surface);border:1px solid var(--border);border-radius:14px;padding:16px"><div style="display:flex;gap:10px;padding:10px 0;border-bottom:1px solid var(--border)"><span style="font-family:var(--font-mono);font-size:12px;font-weight:600;color:var(--accent);background:var(--accent-soft);padding:3px 8px;border-radius:8px;white-space:nowrap">24th Amendment, 1971</span><span style="font-size:13px;color:var(--text2)">Clarified Parliament has power to amend any part including FRs; President must give assent to amendment bills</span></div><div style="display:flex;gap:10px;padding:10px 0"><span style="font-family:var(--font-mono);font-size:12px;font-weight:600;color:var(--accent);background:var(--accent-soft);padding:3px 8px;border-radius:8px;white-space:nowrap">42nd Amendment, 1976</span><span style="font-size:13px;color:var(--text2)">Tried to make amendments immune from judicial review — later struck down in Minerva Mills (1980)</span></div></div></div>`,
  trivia: `<div style="padding:16px"><div style="background:var(--surface);border:1px solid var(--border);border-radius:14px;padding:16px"><ul style="font-size:14px;line-height:1.9;color:var(--text2);padding-left:18px"><li>📊 India's Constitution has been amended <strong>106 times</strong> — making it one of the most amended constitutions in the world</li><li>⚖️ The Kesavananda Bharati case was decided by 7:6 majority — the slimmest possible majority for the most important judgment</li><li>🌍 USA's Constitution has been amended only 27 times in 230+ years; India has done 106 in 75 years</li><li>📋 The <strong>Basic Structure</strong> includes: Supremacy of Constitution, Democratic republic, Secularism, Separation of powers, Judicial review, Federalism, Free and fair elections</li></ul></div></div>`,
  official: `<div style="padding:16px"><div style="font-family:var(--font-mono);font-size:13px;line-height:1.8;color:var(--text2);background:var(--bg2);border-radius:8px;padding:14px;border-left:3px solid var(--accent)"><strong>Article 368. Power of Parliament to amend the Constitution and procedure therefor —</strong><br><br>(1) Notwithstanding anything in this Constitution, Parliament may in exercise of its constituent power amend by way of addition, variation or repeal any provision of this Constitution in accordance with the procedure laid down in this article.<br><br>(2) An amendment of this Constitution may be initiated only by the introduction of a Bill for the purpose in either House of Parliament...[requiring special majority and in some cases state ratification]</div></div>`
}

};

// For articles not in ARTICLE_DATA, return a standard template
function getArticleContent(articleNum, tab, articleTitle, articlePart) {
  const key = String(articleNum);
  if (ARTICLE_DATA[key] && ARTICLE_DATA[key][tab]) {
    return ARTICLE_DATA[key][tab];
  }
  // Default fallback for articles not yet pre-filled
  return getDefaultContent(tab, articleNum, articleTitle, articlePart);
}

function getDefaultContent(tab, n, title, part) {
  const defaults = {
    explain: `<div style="padding:16px"><div style="background:var(--surface);border:1px solid var(--border);border-radius:14px;padding:20px"><div style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:0.8px;color:var(--text3);margin-bottom:10px">💡 Article ${n}: ${title}</div><p style="font-size:14px;line-height:1.7;color:var(--text2)">This article belongs to <strong>${part}</strong>.</p><p style="font-size:14px;line-height:1.7;color:var(--text2);margin-top:8px">📡 For detailed AI-powered explanation, memory tricks and case laws — connect to internet and the app will load fresh content from Gemini AI.</p><p style="font-size:14px;line-height:1.7;color:var(--text2);margin-top:8px">📚 For now, refer to Laxmikanth Chapter on ${part.split('—')[0].trim()} for this article.</p></div></div>`,
    memory: `<div style="padding:16px"><div style="background:linear-gradient(135deg,var(--accent-soft),var(--bg2));border:1px solid var(--accent);border-radius:14px;padding:16px"><div style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:1px;color:var(--accent);margin-bottom:10px">🧠 Quick Memory Tip</div><p style="font-size:14px;line-height:1.7;color:var(--text);font-style:italic">Article ${n} = "${title}". Connect the number ${n} to something in your life — your age, a year, a phone number — to remember this article! 📱 Connect to internet for Bollywood memory tricks.</p></div></div>`,
    exam: `<div style="padding:16px"><div style="background:var(--surface);border:1px solid var(--border);border-radius:14px;padding:16px"><div style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:0.8px;color:var(--text3);margin-bottom:10px">🎓 Exam Relevance</div><p style="font-size:14px;line-height:1.7;color:var(--text2)">Article ${n} (${title}) from ${part}. Check Laxmikanth for exam-specific questions. Connect to internet for AI-powered exam tips tailored for UPSC/BPSC.</p></div></div>`,
    laws: `<div style="padding:16px"><div style="background:var(--surface);border:1px solid var(--border);border-radius:14px;padding:16px"><p style="font-size:14px;line-height:1.7;color:var(--text2)">⚖️ Connect to internet to load landmark Supreme Court cases related to Article ${n}: ${title}.</p></div></div>`,
    amend: `<div style="padding:16px"><div style="background:var(--surface);border:1px solid var(--border);border-radius:14px;padding:16px"><p style="font-size:14px;line-height:1.7;color:var(--text2)">🔄 Connect to internet to load amendment history of Article ${n}: ${title}.</p></div></div>`,
    trivia: `<div style="padding:16px"><div style="background:var(--surface);border:1px solid var(--border);border-radius:14px;padding:16px"><p style="font-size:14px;line-height:1.7;color:var(--text2)">🎯 Connect to internet to load fascinating trivia about Article ${n}: ${title}.</p></div></div>`,
    official: `<div style="padding:16px"><div style="font-family:var(--font-mono);font-size:13px;line-height:1.8;color:var(--text2);background:var(--bg2);border-radius:8px;padding:14px;border-left:3px solid var(--accent)"><strong>Article ${n}. ${title}</strong><br><br>Connect to internet to load the official constitutional text of this article.</div></div>`
  };
  return defaults[tab] || defaults.explain;
}
